### Alice Martins Valero
### Antonio Edézio Santos de Souza
### Luis César Nunes Silveira
### Tauan Neres Silva

# Métodos Diretos

## Eliminação Gaussiana com Substituição Regressiva

In [1]:
import numpy as np


def Gauss_Regressivo(a, n):
    a = np.array(a, dtype=float)
    x = np.zeros(n)

    for i in range(n):
        
        for p in range(i, n):
            if a[p][i] != 0:
                if p != i:
                    a[[i, p]] = a[[p, i]]
        
        if a[i][i] == 0:
            return "Não existe uma solução única para este sistema"

        m = a[i+1:n, i] / a[i][i]
        a[i+1:n, i:] -= np.outer(m, a[i, i:])
    n = n - 1

    if a[n][n] == 0:
        return("Não existe uma solução única para este sistema")
    
    x[n] = a[n][n+1] / a[n][n]

    for i in range(n - 1, -1, -1):
        soma = 0

        for j in range(i + 1, n + 1):
            soma += a[i][j] * x[j]
        
        x[i] = (a[i][n + 1] - soma) / a[i][i]

    return x

### Exemplo 1

In [2]:
matriz = [[1, 1, 1, 1, 1, 5],
          [2, 2, 4, 1, 3, 12],
          [1, 3, 2, 2, 1, 9],
          [4, 1, 1, 5, 2, 13],
          [2, 5, 3, 1, 4, 15]]

n = 5

x_exato = [1, 1, 1, 1, 1]
x = Gauss_Regressivo(matriz, n)

print(f"X obtido usando Gauss com Substituição Regressiva: {x}")
print(f"X exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")

X obtido usando Gauss com Substituição Regressiva: [1. 1. 1. 1. 1.]
X exato: [1, 1, 1, 1, 1]

Resíduos: [-1.59872116e-14 -3.99680289e-15 -1.55431223e-15  9.54791801e-15
  1.17683641e-14]


### Exemplo 2

In [3]:
import numpy as np

matriz = [
    [1e-16, 1, 1, 1, 1, 1, 1, 6],
    [1, 1e-15, 1, 1, 1, 1, 1, 6],
    [1, 1, 1e-15, 1, 1, 1, 1, 6],
    [1, 1, 1, 1e-15, 1, 1, 1, 6],
    [1, 1, 1, 1, 1e-15, 1, 1, 6],
    [1, 1, 1, 1, 1, 1e-15, 1, 6],
    [2, 2, 2, 2, 2, 2, 9e15, 9000000000000012.0]
]
n = 7

x_exato = [1, 1, 1, 1, 1, 1, 1]
x = Gauss_Regressivo(matriz, n)

print(f"X obtido usando Gauss com Substituição Regressiva: {x}")
print(f"X exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")


X obtido usando Gauss com Substituição Regressiva: [1. 1. 1. 1. 1. 1. 1.]
X exato: [1, 1, 1, 1, 1, 1, 1]

Resíduos: [0.00000000e+00 1.11022302e-15 1.11022302e-15 1.11022302e-15
 1.11022302e-15 1.11022302e-15 0.00000000e+00]


## Eliminação Gaussiana com Pivoteamento Parcial

In [4]:
import numpy as np


def Gauss_Parcial(a, n):
    a = np.array(a, dtype=float)
    x = np.zeros(n)

    for i in range(n):

        p = i + np.argmax(np.abs(a[i:n, i]))
        
        if p != i:
            a[[i, p]] = a[[p, i]]
        if a[i][i] == 0:
            return "Não existe uma solução única para este sistema"

        m = a[i+1:n, i] / a[i, i]
        a[i+1:n, i:] -= np.outer(m, a[i, i:])
        
    n = n - 1

    if a[n][n] == 0:
        return("Não existe uma solução única para este sistema")
    
    x[n] = a[n][n+1] / a[n][n]

    for i in range(n - 1, -1, -1):
        soma = 0

        for j in range(i + 1, n + 1):
            soma += a[i][j] * x[j]
        
        x[i] = (a[i][n + 1] - soma) / a[i][i]

    return x

### Exemplo 1

In [5]:
import numpy as np

matriz = [[1, 1, 1, 1, 1, 5],
          [2, 2, 4, 1, 3, 12],
          [1, 3, 2, 2, 1, 9],
          [4, 1, 1, 5, 2, 13],
          [2, 5, 3, 1, 4, 15]]

n = 5

x_exato = [1, 1, 1, 1, 1]
x = Gauss_Parcial(matriz, n)

print(f"X obtido usando Gauss com Pivoteamento Parcial: {x}")
print(f"X exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")


X obtido usando Gauss com Pivoteamento Parcial: [1. 1. 1. 1. 1.]
X exato: [1, 1, 1, 1, 1]

Resíduos: [ 7.10542736e-15  1.99840144e-15  2.22044605e-16 -4.10782519e-15
 -4.99600361e-15]


### Exemplo 2

In [6]:
import numpy as np

matriz = [
    [1e-16, 1, 1, 1, 1, 1, 1, 6],
    [1, 1e-15, 1, 1, 1, 1, 1, 6],
    [1, 1, 1e-15, 1, 1, 1, 1, 6],
    [1, 1, 1, 1e-15, 1, 1, 1, 6],
    [1, 1, 1, 1, 1e-15, 1, 1, 6],
    [1, 1, 1, 1, 1, 1e-15, 1, 6],
    [2, 2, 2, 2, 2, 2, 9e15, 9000000000000012.0]
]
n = 7

x_exato = [1, 1, 1, 1, 1, 1, 1]
x = Gauss_Parcial(matriz, n)

print(f"X obtido usando Gauss com Pivoteamento Parcial: {x}")
print(f"X exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")


X obtido usando Gauss com Pivoteamento Parcial: [ 2. -3.  2.  2.  2.  2.  1.]
X exato: [1, 1, 1, 1, 1, 1, 1]

Resíduos: [ 1.00000000e+00 -4.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00 -2.22044605e-16]


## Eliminação Gaussiana com Pivoteamento Escalado

In [7]:
import numpy as np


def Gauss_Escalado(a, n):
    a = np.array(a, dtype=float)
    x = np.zeros(n)
    s = np.max(np.abs(a[:, :n]), axis=1)

    if np.any(s == 0):
            return "Não existe uma solução única para este sistema"

    for i in range(0, n):

        aux = np.abs(a[i:n, i]) / s[i:n]
        p = i + np.argmax(aux)
        
        if p != i:
            a[[i, p]] = a[[p, i]]
            s[[i, p]] = s[[p, i]]

        if a[i][i] == 0:
            return "Não existe uma solução única para este sistema"

        m = a[i+1:n, i] / a[i][i]
        a[i+1:n, i:] -= np.outer(m, a[i, i:])
        
    n = n - 1

    if a[n][n] == 0:
        return "Não existe uma solução única para este sistema"
    
    x[n] = a[n][n+1] / a[n][n]

    for i in range(n - 1, -1, -1):
        soma = 0

        for j in range(i + 1, n + 1):
            soma += a[i][j] * x[j]
        
        x[i] = (a[i][n + 1] - soma) / a[i][i]

    return x

### Exemplo 1

In [8]:
matriz = [[1, 1, 1, 1, 1, 5],
          [2, 2, 4, 1, 3, 12],
          [1, 3, 2, 2, 1, 9],
          [4, 1, 1, 5, 2, 13],
          [2, 5, 3, 1, 4, 15]]

n = 5

x_exato = [1, 1, 1, 1, 1]
x = Gauss_Escalado(matriz, n)

print(f"X obtido usando Gauss com Pivoteamento Escalado: {x}")
print(f"X exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")

X obtido usando Gauss com Pivoteamento Escalado: [1. 1. 1. 1. 1.]
X exato: [1, 1, 1, 1, 1]

Resíduos: [ 8.88178420e-16  2.22044605e-16  0.00000000e+00 -3.33066907e-16
 -3.33066907e-16]


### Exemplo 2

In [9]:
import numpy as np

matriz = [
    [1e-16,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  6.0],
    [1.0,    1e-15, 1.0,  1.0,  1.0,  1.0,  1.0,  6.0],
    [1.0,    1.0,  1e-15, 1.0,  1.0,  1.0,  1.0,  6.0],
    [1.0,    1.0,  1.0,  1e-15, 1.0,  1.0,  1.0,  6.0],
    [1.0,    1.0,  1.0,  1.0,  1e-15, 1.0,  1.0,  6.0],
    [1.0,    1.0,  1.0,  1.0,  1.0,  1e-15, 1.0,  6.0],
    [2.0,    2.0,  2.0,  2.0,  2.0,  2.0,  9e15, 9000000000000012.0]
]
n = 7

x_exato = [1, 1, 1, 1, 1, 1, 1]
x = Gauss_Escalado(matriz, n)

print(f"X obtido usando Gauss com Pivoteamento Escalado: {x}")
print(f"X exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")


X obtido usando Gauss com Pivoteamento Escalado: [1. 1. 1. 1. 1. 1. 1.]
X exato: [1, 1, 1, 1, 1, 1, 1]

Resíduos: [-8.88178420e-16 -8.88178420e-16 -2.22044605e-16 -1.11022302e-16
  0.00000000e+00  0.00000000e+00  2.22044605e-16]


## Fatoração LU

In [10]:
import numpy as np

def LU (a,n):
    a = np.array(a, dtype=float)
    L = np.eye(n)
    U = np.zeros((n,n))

    U[0, 0:] = a[0, 0:]

    for i in range(n):
        if i != 0:
            U[i, i:] = a[i, i:] - np.dot(L[i, :i], U[:i, i:])

        if U[i, i] == 0:
            raise ValueError("Não existe uma solução única para este sistema")

        if i < n - 1:
            if i == 0:
                L[i+1:, i] = a[i+1:, i] / U[i, i]
            else:
                soma_L = np.dot(L[i+1:, :i], U[:i, i])
                L[i+1:, i] = (a[i+1:, i] - soma_L) / U[i, i]
        
    return L, U

def Fator_LU(L, U, b, n):
    y = np.zeros(n)

    for i in range(n):
        soma = 0
        for j in range(i):
            soma += L[i][j] * y[j]
        y[i] = b[i] - soma
    
    x = np.zeros(n)
    
    for i in range(n - 1, -1, -1):
        soma = 0
        for j in range(i + 1, n):
            soma += U[i][j] * x[j]
        x[i] = (y[i] - soma) / U[i][i]

    return x

### Exemplo 1

In [11]:
a = [[1,  1,  0,  3],
    [2,  1, -1,  1],
    [3, -1, -1,  2],
    [-1,  2,  3, -1]]

b = [8, 7, 14, -7]

n = 4

L,U = LU(a,n)
x = Fator_LU(L, U, b, n)
x_exato = [3, -1, 0, 2]

print(f"X Obtido Usando a Fatoração LU: {x}")
print(f"X Exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")

X Obtido Usando a Fatoração LU: [ 3. -1.  0.  2.]
X Exato: [3, -1, 0, 2]

Resíduos: [0. 0. 0. 0.]


## Fatoração $LDL^t$

In [12]:
def LDL(a, n):
    L = np.eye(n)
    D = np.ones(n)
    v = np.zeros(n)

    for i in range(n):
        somaD = 0
        somaL = 0
        for j in range(i):
            v[j] = L[i][j] * D[j]
            somaD += L[i][j] * v[j]
        
        D[i] = a[i][i] - somaD
    
        for j in range(i + 1, n):
            for k in range(i):
                somaL += L[j][k] * v[k]
            L[j][i] = (a[j][i] - somaL) / D[i]
        
    return L, D

def Fator_LDL(L, D, b, n):
    D = np.diag(D)
    y = np.zeros(n)
    z = np.zeros(n)
    x = np.zeros(n)

    for i in range(n):
        if L[i, i] == 0:
            raise ValueError("Não existe uma solução única para este sistema")
        
        soma = 0
        soma = np.dot(L[i, :i], y[:i])
        y[i] = (b[i] - soma) / L[i, i]
    
    for i in range(n):
        d_elemento = D[i, i] if D.ndim == 2 else D[i]
        
        if d_elemento == 0:
            raise ValueError("Não existe uma solução única para este sistema")
        z[i] = y[i] / d_elemento
        
    for i in range(n - 1, -1, -1):
        soma = 0
        soma = np.dot(L[i+1:, i], x[i+1:])
        x[i] = (z[i] - soma) / L[i, i]

    return x

### Exemplo 1

In [13]:
a = [[4, -1, 1],
    [-1, 4.25, 2],
    [1, 2.75, 3.50]]

b = [1, 4.75, 3]

n = 3

L, D = LDL(a, n)

print(f"{L}\n\n{np.diag(D)}")

x_exato = [1, 2, -1]
x = Fator_LDL(L, D, b, n)

print(f"X Obtido Usando a Fatoração LDL^t: {x}")
print(f"X Exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")

[[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.25  0.75  1.  ]]

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 1.]]
X Obtido Usando a Fatoração LDL^t: [ 1.  2. -1.]
X Exato: [1, 2, -1]

Resíduos: [0. 0. 0.]


## Fatoração de Cholensky

In [14]:
def Cholesky(a,n):
    L = np.zeros((n, n))

    L[0][0] = (a[0][0]) ** 0.5

    for j in range (1, n):
        L[j][0] = a[j][0] / L[0][0]

    for i in range(1, n - 1):
        soma = 0
        for k in range(i):
            soma += L[i][k] ** 2

        L[i][i] = (a[i][i] - soma) ** 0.5

        for j in range (i + 1, n):
            soma = 0
            for k in range(i):
                soma += L[j][k] * L[i][k]
            L[j][i] = (a[i][j] - soma) / L[i][i]
        
        soma = 0
        for k in range(n - 1):
            soma += (L[n - 1][k]) ** 2
        
        L[n - 1][n - 1] = (a[n - 1][n - 1] - soma) ** 0.5

    return L

def Fator_Cholesky(L, Lt, b, n):
    
    y = np.zeros(n)
    x = np.zeros(n)

    for i in range(n):
        soma = np.dot(L[i, :i], y[:i])
        y[i] = (b[i] - soma) / L[i, i]
    
    for i in range(n - 1, -1, -1):
        soma = np.dot(Lt[i, i+1:], x[i+1:])
        x[i] = (y[i] - soma) / Lt[i, i]

    return x

### Exemplo 1

In [15]:
a = [[4, -1, 1],
     [-1, 4.25, 2.75],
     [1, 2.75, 3.5]]

b = [1, 4.75, 3]

n = 3

L = Cholesky(a, n)
Lt = L.T

print(f"{L}\n\n")

print(f"{Lt}\n")

x_exato = [1, 2, -1]
x = Fator_Cholesky(L, Lt, b, n)

print(f"X Obtido Usando a Fatoração LDL^t: {x}")
print(f"X Exato: {x_exato}")

diferenca = x - x_exato

print(f"\nResíduos: {diferenca}")


[[ 2.   0.   0. ]
 [-0.5  2.   0. ]
 [ 0.5  1.5  1. ]]


[[ 2.  -0.5  0.5]
 [ 0.   2.   1.5]
 [ 0.   0.   1. ]]

X Obtido Usando a Fatoração LDL^t: [ 1.  2. -1.]
X Exato: [1, 2, -1]

Resíduos: [0. 0. 0.]


## Fatoração de Crout para Matrizes Tridiagonais

In [16]:
def Crout(a, n):
    a = np.array(a, dtype=float)
    L = np.zeros((n,n))
    U = np.eye(n)

    L[0][0] = a[0][0]
    U[0][1] = a[0][1] / L[0][0]

    for i in range(1, n - 1):
        L[i][i - 1] = a[i][i - 1]
        L[i][i] = a[i][i] - (L[i][i - 1] * U[i - 1][i])
        U[i][i + 1] = a[i][i + 1] / L[i][i]

    n = n - 1
    L[n][n - 1] = a[n][n - 1]
    L[n][n] = a[n][n] - (L[n][n - 1] * U[n - 1][n])

    return L, U

def Fator_Crout(L, U, b, n):
    b = np.array(b, dtype=float)
    Z = np.zeros(n)
    x = np.zeros(n)

    Z[0] = b[0] / L[0, 0]
    for i in range(1, n):
        Z[i] = (b[i] - (L[i, i - 1] * Z[i - 1])) / L[i, i]

    x[n - 1] = Z[n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = Z[i] - (U[i, i + 1] * x[i + 1])

    return x

### Exemplo 1

In [17]:
a = [[2, -1, 0, 0],
    [-1, 2, -1, 0],
    [0, -1, 2, -1],
    [0, 0, -1, 2]]

b = [1, 0, 0, 1]

n = 4

x_exato = [1, 1, 1, 1]
L, U = Crout(a, n)
x = Fator_Crout(L, U, b, n)

print("Matriz L")
print(L)
print("\nMatriz U")
print(U)

print(f"\nX Obtido: {x}")
print(f"\nX Exato:  {x_exato}")
print(f"\nResíduos: {diferenca}")

Matriz L
[[ 2.          0.          0.          0.        ]
 [-1.          1.5         0.          0.        ]
 [ 0.         -1.          1.33333333  0.        ]
 [ 0.          0.         -1.          1.25      ]]

Matriz U
[[ 1.         -0.5         0.          0.        ]
 [ 0.          1.         -0.66666667  0.        ]
 [ 0.          0.          1.         -0.75      ]
 [ 0.          0.          0.          1.        ]]

X Obtido: [1. 1. 1. 1.]

X Exato:  [1, 1, 1, 1]

Resíduos: [0. 0. 0.]


# Métodos Iterativos

## Método de Jacobi

In [18]:
import numpy as np

def Jacobi(a, b, X0, tol = 1e-5, max_iter = 100):
    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)
    X0 = np.array(X0, dtype=float)
    
    D = np.diag(a)
    R = a - np.diag(D)
    
    for i in range(max_iter):
        x = (b - R @ X0) / D
        
        if np.linalg.norm(x - X0) < tol:
            print(f"Método convergiu em {i + 1} iterações.")
            return x
            
        X0 = x
        
    print("O método atingiu o máximo de iterações sem convergir.")
    return x

### Exemplo 1

In [19]:
a = [[10, 2, 1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]
X0 = [0, 0, 0]

x_exato = [0.973, -2.081, 1.430]
x = Jacobi(a, b, X0)

print(f"\nX Obtido: {x}")
print(f"\nX Exato:  {x_exato}")
print(f"\nResíduos: {diferenca}")

Método convergiu em 13 iterações.

X Obtido: [ 0.9999993  -2.00000082  0.99999897]

X Exato:  [0.973, -2.081, 1.43]

Resíduos: [0. 0. 0.]


### Exemplo 2

In [20]:
a = [[10, -1, 2, 0],
     [-1, 11, -1, 3],
     [2, -1, 10, -1],
     [0, 3, -1, 8]]

b = [6, 25, -11, 15]
X0 = [0, 0, 0, 0]

x_exato = [1, 2, -1, 1]
x = Jacobi(a, b, X0)

print(f"\nX Obtido: {x}")
print(f"\nX Exato:  {x_exato}")
print(f"\nResíduos: {diferenca}")

Método convergiu em 16 iterações.

X Obtido: [ 1.00000075  1.99999868 -0.99999899  0.99999862]

X Exato:  [1, 2, -1, 1]

Resíduos: [0. 0. 0.]


## Método de Gauss-Seidel

In [21]:
import numpy as np

def Gauss_Seidel(a, b, X0, tol = 1e-5, max_iter = 100):
    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)
    X0 = np.array(X0, dtype=float)
    x = np.array(X0, dtype=float)

    for k in range(max_iter):
        x_ant = np.copy(x)
        
        for i in range(len(b)):
            x[i] = (b[i] - np.dot(a[i][:i], x[:i]))
            x[i] -= np.dot(a[i][i+1:], x[i+1:]) 
            x[i] /= a[i, i]
            
        if np.linalg.norm(x - x_ant) < tol:
            print(f"Método convergiu em {k + 1} iterações.")
            return x
            
    print("Aviso: O método atingiu o limite de iterações.")
    return x


### Exemplo 1

In [22]:
a = [[10, 2, 1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]
X0 = [0, 0, 0]

x_exato = [0.973, -2.081, 1.430]
x = Gauss_Seidel(a, b, X0)

print(f"\nX Obtido: {x}")
print(f"\nX Exato:  {x_exato}")
print(f"\nResíduos: {diferenca}")

Método convergiu em 7 iterações.

X Obtido: [ 1.00000012 -1.99999992  0.99999995]

X Exato:  [0.973, -2.081, 1.43]

Resíduos: [0. 0. 0.]


### Exemplo 2

In [23]:
a = [[10, -1, 2, 0],
     [-1, 11, -1, 3],
     [2, -1, 10, -1],
     [0, 3, -1, 8]]

b = [6, 25, -11, 15]
X0 = [0, 0, 0, 0]

x_exato = [1, 2, -1, 1]
x = Gauss_Seidel(a, b, X0)

print(f"\nX Obtido: {x}")
print(f"\nX Exato:  {x_exato}")
print(f"\nResíduos: {diferenca}")

Método convergiu em 7 iterações.

X Obtido: [ 1.00000067  2.00000002 -1.00000021  0.99999996]

X Exato:  [1, 2, -1, 1]

Resíduos: [0. 0. 0.]


## Método de Sobrelaxação Sucessiva (SOR)

In [24]:
import numpy as np

def SOR(a, b, n, X0, w, TOL = 1e-5, max_iter = 100):
    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)
    X0 = np.array(X0, dtype=float)
    
    x = np.copy(X0)

    for k in range(max_iter):
        for i in range(n):
            somaA = np.dot(a[i, :i], x[:i])
            
            somaB = np.dot(a[i, i+1:], X0[i+1:])
            
            x[i] = (1 - w) * X0[i] + (w * (-somaA - somaB + b[i])) / a[i, i]

        if np.linalg.norm(x - X0) < TOL:
            print(f"Método convergiu em {k + 1} iterações.")
            return x
        
        X0 = np.copy(x)
        
    print("O método atingiu o máximo de iterações sem convergir.")
    return x

# --- Caso de Teste ---
a = [[10, -1, 2, 0],
     [-1, 11, -1, 3],
     [2, -1, 10, -1],
     [0, 3, -1, 8]]

b = [6, 25, -11, 15]
x_inicial = [0, 0, 0, 0]
w = 1.25  

x_final = SOR(a, b, 4, x_inicial, w)
print(f"Resultado SOR: {x_final}")

Método convergiu em 11 iterações.
Resultado SOR: [ 1.00000045  1.99999823 -0.99999942  1.00000085]


### Exemplo 1

In [25]:
a = [[10, 2, 1],
     [1, 5, 1],
     [2, 3, 10]]

b = [7, -8, 6]
X0 = [0, 0, 0]
n = 3

x_exato = [0.973, -2.081, 1.430]
x = SOR(a, b, n, X0, w)

print(f"\nX Obtido: {x}")
print(f"\nX Exato:  {x_exato}")
print(f"\nResíduos: {diferenca}")

Método convergiu em 11 iterações.

X Obtido: [ 1.00000082 -1.99999838  0.99999971]

X Exato:  [0.973, -2.081, 1.43]

Resíduos: [0. 0. 0.]


### Exemplo 2

In [26]:
a = [[10, -1, 2, 0],
     [-1, 11, -1, 3],
     [2, -1, 10, -1],
     [0, 3, -1, 8]]

b = [6, 25, -11, 15]
X0 = [0, 0, 0, 0]

x_exato = [1, 2, -1, 1]
x = SOR(a, b, n, X0, w)

print(f"\nX Obtido: {x}")
print(f"\nX Exato:  {x_exato}")
print(f"\nResíduos: {diferenca}")

Método convergiu em 11 iterações.

X Obtido: [ 1.043269    2.26923144 -1.08173139  0.        ]

X Exato:  [1, 2, -1, 1]

Resíduos: [0. 0. 0.]
